# Generated by Django 4.0.2 on 2022-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('img_src', models.CharField(max_length=100)),
                ('video_src', models.CharField(max_length=100)),
            ],
        ),
    ]
