# Generated by Django 4.0.2 on 2022-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('img_src', models.CharField(max_length=100)),
                ('video_src', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='places',
        ),
    ]
