# Generated by Django 4.0.2 on 2022-06-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_location_delete_places'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
